name: CI Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: 'write'
      packages: write
      deployments: write
      contents: read
      actions: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B install --file pom.xml

    - name: Coverage
      id: jacoco
      uses: madrapps/jacoco-report@v1.3
      with:
        paths: jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
